apoutchika_media_api_media:
    path:     /
    defaults: { _controller: ApoutchikaMediaBundle:MediaRest:getMedias }
    methods: [GET]
    requirements:

apoutchika_media_api_media_show:
    path:     /{id}
    defaults: { _controller: ApoutchikaMediaBundle:MediaRest:getMedia }
    methods: [GET]
    requirements:
        id: ^\d+$

apoutchika_media_api_media_add:
    path:     /
    defaults: { _controller: ApoutchikaMediaBundle:MediaRest:postMedia }
    methods: [POST]

apoutchika_media_api_media_edit:
    path:     /{id}
    defaults: { _controller: ApoutchikaMediaBundle:MediaRest:putMedia }
    methods: [PUT]
    requirements:
        id: ^\d+$

apoutchika_media_api_media_delete:
    path:     /{id}
    defaults: { _controller: ApoutchikaMediaBundle:MediaRest:deleteMedia }
    methods: [DELETE]
    requirements:
        id: ^\d+$

apoutchika_media_api_media_search:
    path:     /search
    defaults: { _controller: ApoutchikaMediaBundle:MediaRest:searchMedia }
    methods: [GET]
